services:
  rcssserver3d:
    build:
      context: ./rcssserver3d
      dockerfile: Dockerfile
    container_name: rcssserver3d
    ports:
      - "3200:3200"
      - "3100:3100"
    networks:
      rcss3d-network:
        ipv4_address: 10.10.1.2
  rcss3d-roboviz:
    build:
      context: ./roboviz
      dockerfile: Dockerfile
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    environment:
      - DISPLAY=${DISPLAY}
    container_name: rcss3d-roboviz
    command: ["--serverHost=rcssserver3d"]
    depends_on:
      - rcssserver3d
    networks:
      rcss3d-network:
        ipv4_address: 10.10.1.4
  rcss3d-times:
    build:
      context: ./times
      dockerfile: Dockerfile
    container_name: rcss3d-times
    networks:
      rcss3d-network:
        ipv4_address: 10.10.1.3

networks:
  rcss3d-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24